# action.yml
name: 'Publish'
description: 'Publishes the given place to Roblox'
inputs:
  universe-id:
    description: 'Universe ID to publish to'
    required: true

  place-id:
    description: 'Place ID to publish to'
    required: true

  rbx-api-key:
    description: 'The Cloud API key to use when publishing'
    required: true

  placefile:
    description: 'The .rbxl to publish to the place'
    required: true

outputs:
  place-version:
    description: 'The version of the place according to Roblox'
    value: ${{ steps.publish.outputs.place-version }}


runs:
  using: 'composite'
  steps:

  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: Publish
    id: publish
    run: publish.sh
    shell: bash
    env:
      UNIVERSE_ID: ${{ inputs.universe-id }}
      PLACE_ID: ${{ inputs.place-id }}
      RBX_API_KEY: ${{ inputs.rbx-api-key }}
      PLACE_FILE: ${{ inputs.placefile }}
