on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  publish:
    environment: testing
    name: Build place and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
      
      - name: Publish
        env:
          UNIVERSE_ID: ${{ vars.UNIVERSE_ID }}
          PLACE_ID: ${{ vars.PLACE_ID }}
          RBX_API_KEY: ${{ secrets.RBX_API_KEY }}
        run: make publish
