name: Deployment

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  publish:
    if: ${{github.ref == 'refs/heads/main'}}
    environment: 
      name: testing
      url: "https://www.roblox.com/games/${{vars.PLACE_ID}}"
    name: Build place and publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
      
      - name: Build
        run: make build-place

      - name: Publish
        uses: Ulferno/upload-to-roblox@latest
        with:
          universeId: ${{ vars.UNIVERSE_ID }}
          placeId: ${{ vars.PLACE_ID }}
          api-key: ${{ secrets.RBX_API_KEY }}
          file: build/placefile.rbxl
