name: CI/CD

on:
  push:

jobs:

  project-setup:
    name: Checkout and set up project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Setup Rokit
      uses: CompeyDev/setup-rokit@v0.1.2
      with:
        cache: true

  lint:
    name: Run linting checks
    runs-on: ubuntu-latest
    needs: project-setup

    steps:
    - name: Build
      run: make build-place

    - name: Lint setup
      run: make lint-setup

    - name: Lint
      run: make lint

  publish:
    if: ${{github.ref == 'refs/heads/main'}}
    needs: lint

    environment: 
      name: testing
      url: "https://www.roblox.com/games/${{vars.PLACE_ID}}"
    name: Build place and publish
    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: make build-place

      - name: Publish
        uses: Ulferno/upload-to-roblox@latest
        with:
          universeId: ${{ vars.UNIVERSE_ID }}
          placeId: ${{ vars.PLACE_ID }}
          api-key: ${{ secrets.RBX_API_KEY }}
          file: build/placefile.rbxl
