name: Deployment

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  publish:
    environment: 
      name: testing
      url: "https://www.roblox.com/games/${{vars.PLACE_ID}}"
    name: Build place and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: 'v0.3.0'
      
      - name: Build
        run: rojo build -o build/placefile.rbxl

      - name: Publish
        uses: ./.github/actions/rbx-publish
        with:
          universe-id: ${{ vars.UNIVERSE_ID }}
          place-id: ${{ vars.PLACE_ID }}
          rbx-api-key: ${{ secrets.RBX_API_KEY }}
          placefile: build/placefile.rbxl
